"""rename department

Revision ID: 5b95c2d168fd
Revises: c67f89529aca
Create Date: 2024-10-01 13:09:41.002891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b95c2d168fd'
down_revision = 'c67f89529aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # op.create_table('departments',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('address', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # op.create_table('department',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(), nullable=False),
    # sa.Column('address', sa.VARCHAR(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('departments')
    # ### end Alembic commands ###
